services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
    # develop:
    #   watch:
    #     - action: sync
    #       path: ./backend
    #       target: /app/backend
    #     - action: sync
    #       path: ./frontend/dist
    #       target: /app/backend/static
    environment:
      - ENVIRONMENT=production
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONDEVMODE=1
    env_file:
      - .env